export const timerInner = document.querySelector( '.game-data__time-value' )
export const countdown = document.querySelector('.countdown')
export const countdownCircle = document.querySelector('.countdown__circle')
export const wasteContainerTemplate = document.querySelector('#waste-container-template')
export const wasteContainers = document.querySelector('.waste-containers')
export const currentWaste = document.querySelector('.game-data__current-waste') as HTMLElement
export const currentScore = document.querySelector('#current-score') as HTMLElement
export const bestScore = document.querySelector('#best-score') as HTMLElement
export const newRecordBestScore = document.querySelector('.new-record__best-score') as HTMLElement
export const correctAnswerImg = document.querySelector('.answer__correct') as HTMLImageElement
export const incorrectAnswerImg = document.querySelector('.answer__incorrect') as HTMLImageElement
export const modal = document.querySelector('.modal') as HTMLElement
export const closeModalBtn = document.querySelector('.modal__close') as HTMLElement