export const timerInner = document.querySelector( '.countdown__time-value' )
export const countdown = document.querySelector('.countdown')
export const countdownCircle = document.querySelector('.countdown__circle')
export const wasteContainerTemplate = document.querySelector('#waste-container-template')
export const wasteContainers = document.querySelector('.waste-containers')